# coding=utf-8

# write code...
from abc import ABCMeta, abstractmethod

class ModelBase(object, metaclass=ABCMeta):
    """Model Base interface

    Methods:
        train:Trains and generates background model.
        save_model:Saves background model generated by train method to specified file path.
        load__model:Loads background model from specified file path.
    """

    @abstractmethod
    def __init__(self):
        raise NotImplementedError

    @abstractmethod
    def _set_algorithm(self):
        raise NotImplementedError

    @abstractmethod
    def train(self):
        raise NotImplementedError

    @abstractmethod
    def save_model(self):
        raise NotImplementedError

    @abstractmethod
    def load_model(self):
        raise NotImplementedError

    @abstractmethod
    def predict(self):
        raise NotImplementedError


